### ISSUE TITLE
Extendiendo el plugin CakeDC/users de forma transparente

### ISSUE THREAD

**Issue by rogerpro** [cakemojo/todo#10]
El plugin [CakeDC/users](https://github.com/CakeDC/users) ofrece la funcionalidad estándar que tiene cualquier app con usuarios que se registran, loguean, resetean su contraseña, etc. Lo estoy utilizando con una app en **CakePHP 2** y me parece genial.

Ahora bien: normalmente, añadiremos a nuestra app funcionalidad no incluida en el plugin. O (más complicado) integraremos el plugin cuando la app ya tenga un montón de líneas de código con funcionalidad propia en el modelo User y el controlador UsersController.

La [documentación del plugin](https://github.com/CakeDC/users/blob/2.x/Docs/Documentation/Extending-the-Plugin.md) nos indica  cómo extenderlo. Básicamente, se trata de extender el modelo y el controlador llamándolos AppUser y AppUsersController, respectivamente. Esto, en principio, nos obliga a refactorizar código (por ejemplo, cambiando el nombre de modelo 'User' por $this->name en las condiciones de los find). Aparentemente, la refactorización se podría evitar utilizando Model::$alias en el modelo. Pero ello da problemas cuando se añaden condiciones a un find, ya que aunque User sea un alias de AppUser, el find no llega a ejecutarse porque sólo utiliza un alias de tabla.

Por todo ello, me surge la siguiente duda:

**¿Es posible llamar a nuestro modelo User de forma transparente una vez tenemos el plugin CakeDC/users integrado?**

La duda es para una app con CakePHP 2.5.2 que utiliza la [rama 2.x del plugin](https://github.com/CakeDC/users/tree/2.x).

Se agradecen propuestas :)

**Comment by steinkel** [comment]
Ya la discutimos en nuestra pasada reunión.

La respuesta sería migrar CakeDC/Users a 2.8 y luego extender el modelo Users usando AppUsers.
