### ISSUE TITLE
Crear una página sobre cómo configurar un entorno de desarrollo local

### ISSUE THREAD

**Issue by steinkel** [cakemojo/todo#4]
Podemos definir una máquina virtual con los requerimientos que nos hagan falta

**Comment by rogerpro** [comment]
Como primer paso podríamos decir cada uno qué solución usamos. Yo estoy contento con un VirtualBox con Ubuntu Server. Es sólo:
- instalar la iso de Ubuntu
- en la máquina de VirtualBox, configurar red NAT y reenvío de puertos: ssh y http
- $ sudo apt-get install openssh-server
- $ sudo apt-get install lamp-server^

De hecho, lo único que hecho en falta es poder hacer ssh :P. Puedo hacer ssh localhost desde VirtualBox, pero desde fuera no responde, mientras que http responde perfectamente conectando desde fuera. Parece que openssh no permite conexiones desde fuera.

¿Alguna propuesta para arreglarlo?

**Comment by delamux** [comment]
# Instalación de CakePHP en ordenador Local Mac OSX.

## Requisitos para poder instalar CakePHP

Tener instalado **xCode, Homebrew, Nginx o Apache, MySQL y Composer**

### Instalación de XCode:
- Abrimos nuestra terminal y ejecutamos:
  `xcode-select --install`

### Instalación de Homebrew (necesitaremos ruby, pero en mac viene por defecto instalado)
- En nuestra terminal ejecutamos:
  
  `ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`

### Instalamos Nginx:

`brew install nginx`

Para que se ejecute automáticamente, añadimos los archivos a la carpeta LaunchAgents:

`sudo cp /usr/local/opt/nginx/*.plist /Library/LaunchAgents`

Y le damos permisos al usuario root, grupo wheel de todos los archivos .plist que hayan dentro del directorio.

`sudo chown root:wheel /Library/LaunchAgents/*.plist`

### Instalación de PHP

`brew tap homebrew/php`
`brew install php56 --with-fpm --without-apache --with-homebrew-curl --with-homebrew-openssl --without-snmp` 
`brew install php56-mcrypt` 
`brew install php56-ioncubeloader`

Para cambiar las versiones tan simple como esto:
`brew unlink php56`
`brew link php70`

### Instalación de MySQL

`brew install mysql`

Y añadimos el mysql al LaunchAgents

`ln -sfv /usr/local/opt/mysql/*.plist ~/Library/LaunchAgents`

Para ejecutarlo ya:

`launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist`

y en nuestra terminal, ejecutamos:

`mysql_secure_installation` y configuramos el mysql.

### Instalamos composer:

Tan simple como descargarnos el archivo de la web de [composer](https://getcomposer.org/download/)

y moverlo a la carpeta (este proceso es para que podamos ejecutar composer desde cualquier directorio de nuestro equipo):
Esto nos sirve tanto para Linux/Unix/MacOSX, 
`mv composer.phar /usr/local/bin/composer`

## Instalación de Cake PHP 3

Nos vamos al directorio donde queramos crear el proyecto y ejecutamos:

`composer create-project --prefer-dist cakephp/app **nombre-de-nuestra-app**`
