### ISSUE TITLE
Establecer idioma de sesión automáticamente

### ISSUE THREAD

**Issue by rogerpro** [cakemojo/todo#8]
He buscado y no he encontrado un componente (ni opción del core) que haga lo siguiente:
1. Detectar los idiomas aceptados por el navegador.
2. Detectar los idiomas disponibles en la app.
3. Establecer el idioma óptimo para la sesión, que será el primero de los aceptados por el navegador que esté disponible en la app.

Me parece un "must"! :)

**Comment by steinkel** [comment]
Lo tienes aquí:

https://github.com/cakephp/cakephp/blob/master/src/Routing/Filter/LocaleSelectorFilter.php

Saludos!
