### ISSUE TITLE
Dar endorsements en LinkedIn

### ISSUE THREAD

**Issue by rogerpro** [cakemojo/todo#9]
Si estás en CakeMojo sabes CakePHP y sabes que los demás saben CakePHP ;)

Por aquello de hacer networking y de unir fuerzas, estaría bien estar conectados también a través de LinkedIn y darnos "endorsements" (avales) de CakePHP y de los conocimientos derivados (PHP, MVC, SQL, OOP, team management, HTML, CSS, JS, etc).

Así unimos nuestras fuerzas y aprovechamos el potencial de las redes sociales profesionales.

PD: podemos descubrir los perfiles de LinkedIn por la lista de correo, por la web que consta en el perfil de GitHub de cada uno, o añadiendo un comentario aquí.

**Comment by steinkel** [comment]
Personalmente creo que esto vendrá naturalmente a medida que hagamos contribuciones valiosas. El mejor endorsment es tener un PR aceptado en el core...
